[project]
requires-python = ">=3.9"

[tool.poetry]
name = "io_scene_vrm"
version = "1.0.0" # Dummy version. See __init__.bl_info["version"] instead.
description = ""
authors = ["Isamu Mogi <isamu@leafytree.jp>", "iCyP"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.10.*"
bpy = "3.6.*"

[tool.poetry.group.dev.dependencies]
codespell = "*"
mypy = "*"
pyright = "*"
ruff = "*"

[tool.ruff]
allowed-confusables = [
    "\u30ce", # Katakana Letter No
]

[tool.ruff.lint.pep8-naming]
extend-ignore-names = [
    "glTF2ExportUserExtension",
    "glTF2ImportUserExtension",
    "EXPORT_SCENE_OT_*",
    "IMPORT_SCENE_OT_*",
    "ICYP_OT_*",
    "VRM_OT_*",
    "VRM_PT_*",
    "VRM_UL_*",
    "WM_OT_*",
]

[tool.codespell]
ignore-regex = ".* # codespell-ignore"

[tool.mypy]
python_version = "3.9"
strict = true
disallow_any_unimported = true
disallow_any_decorated = true
disallow_any_explicit = true
mypy_path = "$MYPY_CONFIG_FILE_DIR/typings"

[tool.pylint.main]
ignore-paths = "." # Please use Ruff instead.

[tool.pyright]
pythonVersion = "3.9"
pythonPlatform = "All"
typeCheckingMode = "strict"

reportMissingModuleSource = false
reportUnknownArgumentType = false
reportUnknownMemberType = false
reportUnknownVariableType = false
reportImportCycles = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
